- hosts: all
  gather_facts: true
  tasks:
    - name: test hostvars
      debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] }}"
      when:  inventory_hostname == "centosgui" 
      
