- hosts: all
  gather_facts: false
  vars:
     jobids: []
  tasks:
    - name: Task1
      command: /bin/sleep 1
      async: 10
      poll: 0
      when: inventory_hostname == 'centosvm'
      register: result1
   
    - name: Task2
      command: /bin/sleep 1
      async: 10
      poll: 0
      when: inventory_hostname == 'centosgui'
      register: result2


    - name: Task3
      command: /bin/sleep 1
      async: 10
      poll: 0
      when: inventory_hostname == 'j2bb'
      register: result3
    - name: Task4
      command: /bin/sleep 20
      async: 21
      poll: 0
      when: inventory_hostname == 'ubuntu_ldap'
      register: result4
    - name: Task5
      debug:
        var: result1
    - name: Task6
      debug:
        msg: "{{ result1 }}"


    - name: collect job ids
      set_fact:
         jobids: >
                 {% if item.ansible_job_id is defined -%}
                   {{ jobids + [ item.ansible_job_id ] }}
                 {% else -%}
                   {{ jobids }}
                 {% endif %}
      with_items: "{{ [result1,result2,result3,result4] }}"



    - name: show job ids
      debug:
        var: jobids 


    - name: wait for job id
      async_status:
           jid: "{{ item }}"
      with_items: "{{ jobids }}"
      register: job_result
      until: job_result.finished
      retries: 15
