- hosts: all
  tasks:
    - name: forloop demo
      debug:
        msg: >
          {% for entry in ansible_all_ipv4_addresses -%}
               IP Address entry {{ loop.index }} = {{ entry }}
          {% endfor %}
    - name: for in range
      debug:
         msg: >
           {% for item in range(1,11) -%}
               {{ item }}
           {% endfor %}
    - name: for and break
      debug: >
           msg: >
             {% for item in range(10,-1) -%}
                  {% if item == 5 -%}
                     {% break %}
                  {% endif -%}
                  {{ item }}
             {% endfor %}

    - name: for and continue
      debug: >
           msg: >
             {% for item in range(10,-1) -%}
                  {% if item is odd -%}
                     {% continue %}
                  {% endif -%}
                  {{ item }}
             {% endfor %}

