- hosts: all
  tasks:
    - name: install package if sufficient disk space
      yum:
        name: mariadb-server
        state: latest
      with_items: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 20000000000000000
