---
- hosts: all
  user: user
  become: true
  vars:
    system_owner: Navaneetha.k.kannan@oracle.com
  tasks:
    - template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
