backup_tools:
  - backup_files
  - backup_home
  - disk_backup_dirvish
  - find_duplicates
  - report_df
  - reset_cronlog
  - restart_apcmon
  - sudo_dirvish
  - rsync-new
  - test3
dirvish_master: pras

hourly_jobs:
 - check_raid
 - check_space

daily_jobs: []

server_name: server_j2bb
